import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..","..");
const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
const exists=(p)=>fs.existsSync(path.join(root,p));
const CONTROLLER="skills/subagent-driven-development/SKILL.md";
const ROLE_PROMPTS=["skills/subagent-driven-development/prompts/implementer-prompt.md","skills/subagent-driven-development/prompts/task-reviewer-prompt.md","skills/subagent-driven-development/prompts/fix-agent-prompt.md","skills/subagent-driven-development/prompts/final-reviewer-prompt.md"];
const SCHEMAS=["skills/subagent-driven-development/schemas/task-artifact.schema.json","skills/subagent-driven-development/schemas/review-finding.schema.json","skills/subagent-driven-development/schemas/progress-ledger.schema.json"];
const TEMPLATES=["60_templates/PRE_FLIGHT_CONFLICT_REPORT_TEMPLATE.md","60_templates/TASK_BRIEF_TEMPLATE.md","60_templates/IMPLEMENTER_REPORT_TEMPLATE.md","60_templates/TASK_REVIEW_REPORT_TEMPLATE.md","60_templates/FIX_REPORT_TEMPLATE.md","60_templates/FINAL_BRANCH_REVIEW_TEMPLATE.md","60_templates/PROGRESS_LEDGER_TEMPLATE.jsonl"];
test("every role prompt exists",()=>{for(const p of ROLE_PROMPTS)assert.ok(exists(p));});
test("every controller artifact schema exists and is valid JSON",()=>{for(const s of SCHEMAS){assert.ok(exists(s));assert.doesNotThrow(()=>JSON.parse(read(s)));}});
test("every durable controller template exists",()=>{for(const t of TEMPLATES)assert.ok(exists(t));});
test("no controller guidance recommends HEAD~1 shortcut refs",()=>{for(const f of [CONTROLLER,...ROLE_PROMPTS,"skills/subagent-driven-development/ARTIFACT_CONTRACT.md"]){if(!exists(f))continue;for(const line of read(f).split("\n")){if(!line.includes("HEAD~1"))continue;assert.match(line,/prohibit|forbidden|must not|never|reject|do not/i);}}});
test("controller skill mandates a final whole-branch review",()=>{const b=read(CONTROLLER);assert.match(b,/final .*(whole-branch|branch) review/i);assert.match(b,/plan_base_sha\.\.branch_head_sha/);});
test("controller skill mandates material-finding re-review, not fix-attempt clearing",()=>{const b=read(CONTROLLER);assert.match(b,/FIXED_PENDING_REVIEW/);assert.match(b,/A fix attempt does not clear a finding/i);assert.match(b,/CLEARED/);});
test("controller skill defines pre-flight conflict scan before task 1",()=>{const b=read(CONTROLLER);assert.match(b,/pre-flight conflict scan/i);assert.match(b,/before task 1/i);});
test("controller skill defines a bounded repair budget",()=>{const b=read(CONTROLLER);assert.match(b,/repair budget/i);assert.match(b,/BLOCKED/);});
test("controller skill defines CANNOT_VERIFY_FROM_DIFF mapped to Unknown",()=>{const b=read(CONTROLLER);assert.match(b,/CANNOT_VERIFY_FROM_DIFF/);assert.match(b,/Unknown/);});
test("controller skill enforces reviewer neutrality and independence",()=>{const b=read(CONTROLLER);assert.match(b,/neutrality/i);assert.match(b,/verbatim/i);assert.match(b,/independen/i);});
test("controller skill enforces context-cost controls via file-based handoff",()=>{assert.match(read(CONTROLLER),/paths?\b.*(not|rather than).*(paste|full)|file-based handoff/i);});
test("artifact contract exists and forbids secrets in artifacts",()=>{const f="skills/subagent-driven-development/ARTIFACT_CONTRACT.md";assert.ok(exists(f));assert.match(read(f),/secret|credential|token/i);});
test("controller skill uses only canonical evidence vocabulary",()=>{const b=read(CONTROLLER);for(const x of ["Inconclusive","Not Applicable"])assert.ok(!b.includes(x));});
