import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validateAgainstSchema } from "../lib/json-schema.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..","..");
const read=(p)=>JSON.parse(fs.readFileSync(path.join(root,p),"utf8"));
const MANIFEST_SCHEMA=read("runtime_adapters/schemas/adapter-manifest.schema.json");
const MAPPING_SCHEMA=read("runtime_adapters/schemas/tool-mapping.schema.json");
const REQUIRED_RUNTIMES=["codex","cursor","github-copilot","claude","gemini","replit","manus","generic-agent"];
const okManifest=()=>read("runtime_adapters/manifests/claude.json");
const okMapping=()=>read("runtime_adapters/tool_mappings/claude.json");
const expectInvalid=(schema,doc,pattern,label)=>{const errors=validateAgainstSchema(schema,doc);assert.ok(errors.length>0,`schema accepted an invalid document: ${label}`);assert.match(errors.join(" | "),pattern);};
test("every shipped manifest validates against the published schema",()=>{for(const r of REQUIRED_RUNTIMES)assert.deepEqual(validateAgainstSchema(MANIFEST_SCHEMA,read(`runtime_adapters/manifests/${r}.json`)),[]);});
test("every shipped tool mapping validates against the published schema",()=>{for(const r of REQUIRED_RUNTIMES)assert.deepEqual(validateAgainstSchema(MAPPING_SCHEMA,read(`runtime_adapters/tool_mappings/${r}.json`)),[]);});
test("invalid install_scope is rejected",()=>{const m=okManifest();m.install_scope="everywhere";expectInvalid(MANIFEST_SCHEMA,m,/install_scope/,"install_scope");});
test("unsupported operating system is rejected",()=>{const m=okManifest();m.supported_operating_systems=["solaris"];expectInvalid(MANIFEST_SCHEMA,m,/supported_operating_systems/,"os enum");});
test("empty operating-system list is rejected",()=>{const m=okManifest();m.supported_operating_systems=[];expectInvalid(MANIFEST_SCHEMA,m,/supported_operating_systems/,"minItems");});
test("non-boolean modifies_user_files is rejected",()=>{const m=okManifest();m.modifies_user_files="no";expectInvalid(MANIFEST_SCHEMA,m,/modifies_user_files/,"boolean type");});
test("runtime_id violating its pattern is rejected",()=>{const m=okManifest();m.runtime_id="Not A Valid ID";expectInvalid(MANIFEST_SCHEMA,m,/runtime_id/,"pattern");});
test("invalid capability availability is rejected",()=>{const m=okManifest();m.capabilities.file_read="sort_of";expectInvalid(MANIFEST_SCHEMA,m,/file_read/,"availability enum");});
test("undeclared manifest property is rejected",()=>{const m=okManifest();m.totally_made_up_field="hello";expectInvalid(MANIFEST_SCHEMA,m,/totally_made_up_field/,"additionalProperties");});
test("undeclared mapping property is rejected",()=>{const mp=okMapping();mp.sneaky=true;expectInvalid(MAPPING_SCHEMA,mp,/sneaky/,"additionalProperties");});
test("undeclared action property is rejected",()=>{const mp=okMapping();mp.actions.read_file.extra_field=1;expectInvalid(MAPPING_SCHEMA,mp,/extra_field/,"nested additionalProperties");});
test("undeclared action name is rejected",()=>{const mp=okMapping();mp.actions.launch_missiles={availability:"native",mechanism:"x"};expectInvalid(MAPPING_SCHEMA,mp,/launch_missiles/,"undeclared action");});
test("missing required manifest field is rejected",()=>{const m=okManifest();delete m.rollback;expectInvalid(MANIFEST_SCHEMA,m,/rollback/,"required");});
test("action missing required_parameters is rejected",()=>{const mp=okMapping();delete mp.actions.read_file.required_parameters;expectInvalid(MAPPING_SCHEMA,mp,/required_parameters/,"required action field");});
test("action missing evidence_produced is rejected",()=>{const mp=okMapping();delete mp.actions.write_file.evidence_produced;expectInvalid(MAPPING_SCHEMA,mp,/evidence_produced/,"required action field");});
test("missing required capability key is rejected",()=>{const m=okManifest();delete m.capabilities.subagents;expectInvalid(MANIFEST_SCHEMA,m,/subagents/,"required capability");});
test("activation marker must match the exact documented form",()=>{const m=okManifest();m.activation_marker="claude";expectInvalid(MANIFEST_SCHEMA,m,/activation_marker/,"marker pattern");});
test("shipped markers match WCBS_KIT_ACTIVE:<runtime-id> exactly",()=>{for(const r of REQUIRED_RUNTIMES)assert.equal(read(`runtime_adapters/manifests/${r}.json`).activation_marker,`WCBS_KIT_ACTIVE:${r}`);});
const TASK_SCHEMA=read("skills/subagent-driven-development/schemas/task-artifact.schema.json");
const FINDING_SCHEMA=read("skills/subagent-driven-development/schemas/review-finding.schema.json");
const LEDGER_SCHEMA=read("skills/subagent-driven-development/schemas/progress-ledger.schema.json");
const okTask=()=>read("scripts/tests/fixtures/run-bundle/tasks/T-01/task-artifact.json");
const okFinding=()=>({finding_id:"F-100",run_id:"R",task_id:"T",severity:"IMPORTANT",state:"OPEN",summary:"s",evidence:[{file:"a.js",line:1}],opened_by:"final_reviewer",opened_utc:"2026-07-11T00:00:00Z",repair_budget:3,repair_rounds_used:0});
const okLedger=()=>({run_id:"R",task_id:"T",recorded_utc:"2026-07-11T00:00:00Z",task_base_sha:"0".repeat(40),status:"DONE",review_verdict:"PASS",evidence_state:"Verified",findings_opened:0,tests_run:[{command:"npm test",exit_status:0,result:"all passed"}]});
test("baseline fixtures are schema-valid",()=>{assert.deepEqual(validateAgainstSchema(TASK_SCHEMA,okTask()),[]);assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,okFinding()),[]);assert.deepEqual(validateAgainstSchema(LEDGER_SCHEMA,okLedger()),[]);});
test("minimum is enforced: repair_budget below 1 is rejected",()=>{const f=okFinding();f.repair_budget=0;expectInvalid(FINDING_SCHEMA,f,/repair_budget/,"minimum: 1");});
test("minimum is enforced: negative repair_rounds_used is rejected",()=>{const f=okFinding();f.repair_rounds_used=-1;expectInvalid(FINDING_SCHEMA,f,/repair_rounds_used/,"minimum: 0");});
test("minimum is enforced: negative ledger counters are rejected",()=>{const l=okLedger();l.findings_opened=-1;expectInvalid(LEDGER_SCHEMA,l,/findings_opened/,"minimum: 0");});
test("format date-time is enforced on a finding timestamp",()=>{const f=okFinding();f.opened_utc="not-a-date";expectInvalid(FINDING_SCHEMA,f,/opened_utc/,"format: date-time");});
test("format date-time is enforced on a ledger timestamp",()=>{const l=okLedger();l.recorded_utc="not-a-date";expectInvalid(LEDGER_SCHEMA,l,/recorded_utc/,"format: date-time");});
test("a valid RFC 3339 timestamp with an offset is accepted",()=>{const f=okFinding();f.opened_utc="2026-07-11T12:30:00+02:00";assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,f),[]);});
test("a real date with an impossible day is rejected",()=>{const f=okFinding();f.opened_utc="2026-02-31T00:00:00Z";expectInvalid(FINDING_SCHEMA,f,/opened_utc/,"impossible calendar date");});
test("the validator rejects an unsupported keyword in a visited property",()=>{const s={type:"object",properties:{x:{type:"number",exclusiveMinimum:5}}};assert.throws(()=>validateAgainstSchema(s,{x:1}),/unsupported schema keyword/i);});
test("the validator rejects an unsupported keyword in an absent optional property",()=>{const s={type:"object",properties:{x:{type:"number",exclusiveMinimum:5}}};assert.throws(()=>validateAgainstSchema(s,{}),/unsupported schema keyword/i);});
test("the validator rejects an unsupported keyword in an unused $defs entry",()=>{const s={type:"object",$defs:{hidden:{type:"number",exclusiveMinimum:5}}};assert.throws(()=>validateAgainstSchema(s,{}),/unsupported schema keyword/i);});
test("$ref sibling assertions are enforced",()=>{const s={$defs:{n:{type:"number"}},$ref:"#/$defs/n",minimum:5};assert.match(validateAgainstSchema(s,1).join(" | "),/below minimum 5/);assert.deepEqual(validateAgainstSchema(s,5),[]);});
test("RFC 3339 date-time rejects out-of-range timezone offsets",()=>{for(const v of ["2026-07-11T12:30:00+99:00","2026-07-11T12:30:00+02:99"]){const f=okFinding();f.opened_utc=v;expectInvalid(FINDING_SCHEMA,f,/opened_utc/,v);}});
test("RFC 3339 date-time accepts valid boundary offsets",()=>{for(const v of ["2026-07-11T12:30:00+23:59","2026-07-11T12:30:00-23:59"]){const f=okFinding();f.opened_utc=v;assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,f),[]);}});
test("leap second 60 is accepted only at an offset-adjusted month boundary",()=>{const valid=okFinding();valid.opened_utc="2026-06-30T23:59:60Z";assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,valid),[]);for(const v of ["2026-06-30T12:00:60Z","2026-06-29T23:59:60Z"]){const f=okFinding();f.opened_utc=v;expectInvalid(FINDING_SCHEMA,f,/opened_utc/,v);}});
test("malformed supported keywords are rejected during preflight",()=>{for(const schema of [{type:"object",properties:[]},{type:"object",required:"x"},{type:"number",minimum:"5"},{enum:"x"},{type:[]}])assert.throws(()=>validateAgainstSchema(schema,{}),/malformed supported keyword/i);});
test("contradictory numeric bounds are rejected during preflight",()=>{assert.throws(()=>validateAgainstSchema({type:"number",minimum:10,maximum:1},5),/minimum cannot exceed maximum/i);});
test("cleared lifecycle timestamps must be RFC 3339 date-time",()=>{const f=okFinding();f.state="CLEARED";f.cleared_by="final_reviewer";f.cleared_utc="yesterday";expectInvalid(FINDING_SCHEMA,f,/cleared_utc/,"cleared timestamp");});
test("finding history timestamps must be RFC 3339 date-time",()=>{const f=okFinding();f.history=[{from:"OPEN",to:"FIXED_PENDING_REVIEW",actor:"fix_agent",utc:"soon"}];expectInvalid(FINDING_SCHEMA,f,/history.*utc|not a valid date-time/,"history timestamp");});
test("a fix agent cannot be recorded as the clearing authority",()=>{const f=okFinding();f.cleared_by="fix_agent";expectInvalid(FINDING_SCHEMA,f,/cleared_by/,"clearing authority");});
test("progress-ledger test evidence requires a result",()=>{const l=okLedger();delete l.tests_run[0].result;expectInvalid(LEDGER_SCHEMA,l,/result/,"test evidence result");});
test("task artifacts require immutable-brief contract fields",()=>{const task=okTask();delete task.brief_revision;expectInvalid(TASK_SCHEMA,task,/brief_revision/,"brief revision");});

const CAPABILITY_RESOLUTION_SCHEMA=read("runtime_adapters/schemas/capability-resolution.schema.json");
const ELITE_GOALS_LEDGER_SCHEMA=read("runtime_adapters/schemas/elite-goals-ledger.schema.json");
const EVIDENCE_LEDGER_SCHEMA=read("runtime_adapters/schemas/evidence-ledger.schema.json");
const RISK_REGISTER_SCHEMA=read("runtime_adapters/schemas/risk-register.schema.json");
const RELEASE_STATE_SCHEMA=read("runtime_adapters/schemas/release-state.schema.json");
const states=["Verified","Likely","Suspected","Unknown","Not Run","Blocked"];
const okCapabilityResolution=()=>({project_id:"P-1",capabilities:[{id:"security",applicable:false,justification:"No security-sensitive surface is in scope.",subcapabilities:[],resolved_skills:[],resolved_audits:[],resolved_templates:[],resolved_gates:[],ceiling:"Manual"}],evidence_state:"Verified",resolved_at:"2026-07-27T14:00:00Z"});
const okEliteGoalsLedger=()=>({project_id:"P-1",goals:Array.from({length:17},(_,index)=>({goal_id:index===0?"META_GOAL_0":`GOAL_${index}`,applicable:true,execution_path:`path/execution-${index}.md`,verification_path:`path/verification-${index}.json`,evidence_state:"Verified"})),updated_at:"2026-07-27T14:00:00Z"});
const okEvidenceLedgerRecord=()=>({ts:"2026-07-27T14:00:00Z",state:"Verified",claim:"Initialization authority loaded.",source:"00_start_here/SOURCE_OF_TRUTH.md",phase:"LOAD_AUTHORITY"});
const okRiskRegister=()=>({project_id:"P-1",risks:[{id:"R-1",description:"A required capability may be unavailable.",likelihood:"Low",impact:"High",owner:"controller",mitigation:"Block initialization when routing is absent.",status:"Open",evidence_state:"Verified"}],updated_at:"2026-07-27T14:00:00Z"});
const gate=()=>({status:"PASS",evidence_state:"Verified",summary:"Gate evidence is complete."});
const okReleaseState=()=>({verdict:"PASS",gates:Object.fromEntries("ABCDEFGHI".split("").map((id)=>[id,gate()])),blockers:[],accepted_risks:[],updated_at:"2026-07-27T14:00:00Z"});
test("all five bootstrap artifact schemas accept valid baseline instances",()=>{for(const [schema,doc] of [[CAPABILITY_RESOLUTION_SCHEMA,okCapabilityResolution()],[ELITE_GOALS_LEDGER_SCHEMA,okEliteGoalsLedger()],[EVIDENCE_LEDGER_SCHEMA,okEvidenceLedgerRecord()],[RISK_REGISTER_SCHEMA,okRiskRegister()],[RELEASE_STATE_SCHEMA,okReleaseState()]])assert.deepEqual(validateAgainstSchema(schema,doc),[]);});
test("capability resolution requires unconditional non-empty justification",()=>{const doc=okCapabilityResolution();delete doc.capabilities[0].justification;expectInvalid(CAPABILITY_RESOLUTION_SCHEMA,doc,/justification/,"missing capability justification");doc.capabilities[0].justification="";expectInvalid(CAPABILITY_RESOLUTION_SCHEMA,doc,/justification/,"empty capability justification");});
test("elite goals ledger requires exactly 17 rows and non-empty verification paths",()=>{const short=okEliteGoalsLedger();short.goals.pop();expectInvalid(ELITE_GOALS_LEDGER_SCHEMA,short,/minItems/,"missing elite goal row");const empty=okEliteGoalsLedger();empty.goals[0].verification_path="";expectInvalid(ELITE_GOALS_LEDGER_SCHEMA,empty,/verification_path/,"empty verification path");});
test("bootstrap artifact evidence states use only the canonical six-state vocabulary",()=>{for(const [schema,doc,setter] of [[CAPABILITY_RESOLUTION_SCHEMA,okCapabilityResolution(),(d)=>d.evidence_state="Proven"],[ELITE_GOALS_LEDGER_SCHEMA,okEliteGoalsLedger(),(d)=>d.goals[0].evidence_state="Proven"],[EVIDENCE_LEDGER_SCHEMA,okEvidenceLedgerRecord(),(d)=>d.state="Proven"],[RISK_REGISTER_SCHEMA,okRiskRegister(),(d)=>d.risks[0].evidence_state="Proven"],[RELEASE_STATE_SCHEMA,okReleaseState(),(d)=>d.gates.A.evidence_state="Proven"]]){setter(doc);expectInvalid(schema,doc,/evidence_state|state/,"non-canonical evidence state");}assert.equal(states.length,6);});
test("evidence-ledger schema validates one JSONL record and rejects malformed timestamps",()=>{const record=okEvidenceLedgerRecord();record.ts="today";expectInvalid(EVIDENCE_LEDGER_SCHEMA,record,/ts/,"invalid JSONL timestamp");expectInvalid(EVIDENCE_LEDGER_SCHEMA,[okEvidenceLedgerRecord()],/expected type object/,"JSONL must validate per line, not as an array");});
test("risk register constrains status and impact vocabularies",()=>{const doc=okRiskRegister();doc.risks[0].status="Maybe";expectInvalid(RISK_REGISTER_SCHEMA,doc,/status/,"risk status");doc.risks[0].status="Open";doc.risks[0].impact="Catastrophic";expectInvalid(RISK_REGISTER_SCHEMA,doc,/impact/,"risk impact");});
test("release state requires Gates A through I and canonical verdicts",()=>{const missing=okReleaseState();delete missing.gates.I;expectInvalid(RELEASE_STATE_SCHEMA,missing,/missing required property "I"/,"missing release gate");const verdict=okReleaseState();verdict.verdict="GREEN";expectInvalid(RELEASE_STATE_SCHEMA,verdict,/verdict/,"non-canonical release verdict");});
