import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validateAgainstSchema } from "../lib/json-schema.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..","..");
const read=(p)=>JSON.parse(fs.readFileSync(path.join(root,p),"utf8"));
const MANIFEST_SCHEMA=read("runtime_adapters/schemas/adapter-manifest.schema.json");
const MAPPING_SCHEMA=read("runtime_adapters/schemas/tool-mapping.schema.json");
const REQUIRED_RUNTIMES=["codex","cursor","github-copilot","claude","gemini","replit","manus","generic-agent"];
const okManifest=()=>read("runtime_adapters/manifests/claude.json");
const okMapping=()=>read("runtime_adapters/tool_mappings/claude.json");
const expectInvalid=(schema,doc,pattern,label)=>{const errors=validateAgainstSchema(schema,doc);assert.ok(errors.length>0,`schema accepted an invalid document: ${label}`);assert.match(errors.join(" | "),pattern);};
test("every shipped manifest validates against the published schema",()=>{for(const r of REQUIRED_RUNTIMES)assert.deepEqual(validateAgainstSchema(MANIFEST_SCHEMA,read(`runtime_adapters/manifests/${r}.json`)),[]);});
test("every shipped tool mapping validates against the published schema",()=>{for(const r of REQUIRED_RUNTIMES)assert.deepEqual(validateAgainstSchema(MAPPING_SCHEMA,read(`runtime_adapters/tool_mappings/${r}.json`)),[]);});
test("invalid install_scope is rejected",()=>{const m=okManifest();m.install_scope="everywhere";expectInvalid(MANIFEST_SCHEMA,m,/install_scope/,"install_scope");});
test("unsupported operating system is rejected",()=>{const m=okManifest();m.supported_operating_systems=["solaris"];expectInvalid(MANIFEST_SCHEMA,m,/supported_operating_systems/,"os enum");});
test("empty operating-system list is rejected",()=>{const m=okManifest();m.supported_operating_systems=[];expectInvalid(MANIFEST_SCHEMA,m,/supported_operating_systems/,"minItems");});
test("non-boolean modifies_user_files is rejected",()=>{const m=okManifest();m.modifies_user_files="no";expectInvalid(MANIFEST_SCHEMA,m,/modifies_user_files/,"boolean type");});
test("runtime_id violating its pattern is rejected",()=>{const m=okManifest();m.runtime_id="Not A Valid ID";expectInvalid(MANIFEST_SCHEMA,m,/runtime_id/,"pattern");});
test("invalid capability availability is rejected",()=>{const m=okManifest();m.capabilities.file_read="sort_of";expectInvalid(MANIFEST_SCHEMA,m,/file_read/,"availability enum");});
test("undeclared manifest property is rejected",()=>{const m=okManifest();m.totally_made_up_field="hello";expectInvalid(MANIFEST_SCHEMA,m,/totally_made_up_field/,"additionalProperties");});
test("undeclared mapping property is rejected",()=>{const mp=okMapping();mp.sneaky=true;expectInvalid(MAPPING_SCHEMA,mp,/sneaky/,"additionalProperties");});
test("undeclared action property is rejected",()=>{const mp=okMapping();mp.actions.read_file.extra_field=1;expectInvalid(MAPPING_SCHEMA,mp,/extra_field/,"nested additionalProperties");});
test("undeclared action name is rejected",()=>{const mp=okMapping();mp.actions.launch_missiles={availability:"native",mechanism:"x"};expectInvalid(MAPPING_SCHEMA,mp,/launch_missiles/,"undeclared action");});
test("missing required manifest field is rejected",()=>{const m=okManifest();delete m.rollback;expectInvalid(MANIFEST_SCHEMA,m,/rollback/,"required");});
test("action missing required_parameters is rejected",()=>{const mp=okMapping();delete mp.actions.read_file.required_parameters;expectInvalid(MAPPING_SCHEMA,mp,/required_parameters/,"required action field");});
test("action missing evidence_produced is rejected",()=>{const mp=okMapping();delete mp.actions.write_file.evidence_produced;expectInvalid(MAPPING_SCHEMA,mp,/evidence_produced/,"required action field");});
test("missing required capability key is rejected",()=>{const m=okManifest();delete m.capabilities.subagents;expectInvalid(MANIFEST_SCHEMA,m,/subagents/,"required capability");});
test("activation marker must match the exact documented form",()=>{const m=okManifest();m.activation_marker="claude";expectInvalid(MANIFEST_SCHEMA,m,/activation_marker/,"marker pattern");});
test("shipped markers match WCBS_KIT_ACTIVE:<runtime-id> exactly",()=>{for(const r of REQUIRED_RUNTIMES)assert.equal(read(`runtime_adapters/manifests/${r}.json`).activation_marker,`WCBS_KIT_ACTIVE:${r}`);});
const FINDING_SCHEMA=read("skills/subagent-driven-development/schemas/review-finding.schema.json");
const LEDGER_SCHEMA=read("skills/subagent-driven-development/schemas/progress-ledger.schema.json");
const okFinding=()=>({finding_id:"F-100",run_id:"R",task_id:"T",severity:"IMPORTANT",state:"OPEN",summary:"s",evidence:[{file:"a.js",line:1}],opened_by:"final_reviewer",opened_utc:"2026-07-11T00:00:00Z",repair_budget:3,repair_rounds_used:0});
const okLedger=()=>({run_id:"R",task_id:"T",recorded_utc:"2026-07-11T00:00:00Z",task_base_sha:"0".repeat(40),status:"DONE",review_verdict:"PASS",evidence_state:"Verified",findings_opened:0});
test("baseline fixtures are schema-valid",()=>{assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,okFinding()),[]);assert.deepEqual(validateAgainstSchema(LEDGER_SCHEMA,okLedger()),[]);});
test("minimum is enforced: repair_budget below 1 is rejected",()=>{const f=okFinding();f.repair_budget=0;expectInvalid(FINDING_SCHEMA,f,/repair_budget/,"minimum: 1");});
test("minimum is enforced: negative repair_rounds_used is rejected",()=>{const f=okFinding();f.repair_rounds_used=-1;expectInvalid(FINDING_SCHEMA,f,/repair_rounds_used/,"minimum: 0");});
test("minimum is enforced: negative ledger counters are rejected",()=>{const l=okLedger();l.findings_opened=-1;expectInvalid(LEDGER_SCHEMA,l,/findings_opened/,"minimum: 0");});
test("format date-time is enforced on a finding timestamp",()=>{const f=okFinding();f.opened_utc="not-a-date";expectInvalid(FINDING_SCHEMA,f,/opened_utc/,"format: date-time");});
test("format date-time is enforced on a ledger timestamp",()=>{const l=okLedger();l.recorded_utc="not-a-date";expectInvalid(LEDGER_SCHEMA,l,/recorded_utc/,"format: date-time");});
test("a valid RFC 3339 timestamp with an offset is accepted",()=>{const f=okFinding();f.opened_utc="2026-07-11T12:30:00+02:00";assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,f),[]);});
test("a real date with an impossible day is rejected",()=>{const f=okFinding();f.opened_utc="2026-02-31T00:00:00Z";expectInvalid(FINDING_SCHEMA,f,/opened_utc/,"impossible calendar date");});
test("the validator rejects an unsupported keyword in a visited property",()=>{const s={type:"object",properties:{x:{type:"number",exclusiveMinimum:5}}};assert.throws(()=>validateAgainstSchema(s,{x:1}),/unsupported schema keyword/i);});
test("the validator rejects an unsupported keyword in an absent optional property",()=>{const s={type:"object",properties:{x:{type:"number",exclusiveMinimum:5}}};assert.throws(()=>validateAgainstSchema(s,{}),/unsupported schema keyword/i);});
test("the validator rejects an unsupported keyword in an unused $defs entry",()=>{const s={type:"object",$defs:{hidden:{type:"number",exclusiveMinimum:5}}};assert.throws(()=>validateAgainstSchema(s,{}),/unsupported schema keyword/i);});
test("$ref sibling assertions are enforced",()=>{const s={$defs:{n:{type:"number"}},$ref:"#/$defs/n",minimum:5};assert.match(validateAgainstSchema(s,1).join(" | "),/below minimum 5/);assert.deepEqual(validateAgainstSchema(s,5),[]);});
test("RFC 3339 date-time rejects out-of-range timezone offsets",()=>{for(const v of ["2026-07-11T12:30:00+99:00","2026-07-11T12:30:00+02:99"]){const f=okFinding();f.opened_utc=v;expectInvalid(FINDING_SCHEMA,f,/opened_utc/,v);}});
test("RFC 3339 date-time accepts valid boundary offsets",()=>{for(const v of ["2026-07-11T12:30:00+23:59","2026-07-11T12:30:00-23:59"]){const f=okFinding();f.opened_utc=v;assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,f),[]);}});
test("leap second 60 is accepted only at an offset-adjusted month boundary",()=>{const valid=okFinding();valid.opened_utc="2026-06-30T23:59:60Z";assert.deepEqual(validateAgainstSchema(FINDING_SCHEMA,valid),[]);for(const v of ["2026-06-30T12:00:60Z","2026-06-29T23:59:60Z"]){const f=okFinding();f.opened_utc=v;expectInvalid(FINDING_SCHEMA,f,/opened_utc/,v);}});
