/**
 * Doctor integration tests (plan C1: scripts/tests/wcbs-doctor.test.mjs).
 *
 * The other suites test the validators. This suite tests THE DOCTOR: it copies
 * the repository to a scratch fixture, mutates exactly one contract, invokes
 * scripts/wcbs-doctor.mjs as a subprocess, and asserts a nonzero exit with the
 * expected failure.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..","..");
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"wcbs-doctor-"));fs.cpSync(root,dir,{recursive:true,filter:(src)=>{const b=path.basename(src);return b!==".git"&&b!=="node_modules"&&b!=="__pycache__";}});return dir;}
function runDoctor(dir){const r=spawnSync(process.execPath,[path.join(dir,"scripts","wcbs-doctor.mjs")],{cwd:dir,encoding:"utf8"});return{code:r.status,output:`${r.stdout}${r.stderr}`};}
const readJson=(dir,rel)=>JSON.parse(fs.readFileSync(path.join(dir,rel),"utf8"));
const writeJson=(dir,rel,v)=>fs.writeFileSync(path.join(dir,rel),`${JSON.stringify(v,null,2)}\n`);
const readText=(dir,rel)=>fs.readFileSync(path.join(dir,rel),"utf8");
const writeText=(dir,rel,v)=>fs.writeFileSync(path.join(dir,rel),v);
const FIXTURE_RUN=".wcbs/runs/RUN-FIXTURE";
function installRunBundle(dir){const target=path.join(dir,FIXTURE_RUN);fs.mkdirSync(target,{recursive:true});for(const file of ["findings.json","progress-ledger.jsonl"])fs.copyFileSync(path.join(dir,"scripts/tests/fixtures/run-bundle",file),path.join(target,file));return dir;}
function assertDoctorRejects(mutate,expected,label){const dir=fixture();try{const before=runDoctor(dir);assert.equal(before.code,0,`fixture did not pass before mutation: ${before.output}`);mutate(dir);const after=runDoctor(dir);assert.notEqual(after.code,0,`doctor ACCEPTED a contract violation: ${label}`);assert.match(after.output,expected,`doctor failed for the wrong reason: ${label}`);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test("the unmutated repository passes the doctor",()=>{const dir=fixture();try{const{code,output}=runDoctor(dir);assert.equal(code,0,output);assert.match(output,/^PASS:/m);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test("doctor rejects a Full adapter with a manual bootstrap",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/manus.json");m.support_level="Full";writeJson(dir,"runtime_adapters/manifests/manus.json",m);},/bootstrap_mode|Full/i,"Full label on a manual bootstrap"));
test("doctor rejects a supported adapter missing an essential capability",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/generic-agent.json");m.capabilities.execute_command="unavailable";m.fallbacks.execute_command="none";writeJson(dir,"runtime_adapters/manifests/generic-agent.json",m);},/essential/i,"essential capability unavailable but not Unsupported"));
test("doctor rejects a non-native capability with no fallback",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/gemini.json");delete m.fallbacks.subagents;writeJson(dir,"runtime_adapters/manifests/gemini.json",m);},/fallback/i,"missing fallback"));
test("doctor rejects an undeclared manifest property",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/claude.json");m.smuggled_field="hello";writeJson(dir,"runtime_adapters/manifests/claude.json",m);},/undeclared property|smuggled_field/i,"additionalProperties: false"));
test("doctor rejects an unsupported operating system",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/claude.json");m.supported_operating_systems=["solaris"];writeJson(dir,"runtime_adapters/manifests/claude.json",m);},/supported_operating_systems/i,"os enum"));
test("doctor rejects a mapping action missing evidence_produced",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/tool_mappings/claude.json");delete m.actions.write_file.evidence_produced;writeJson(dir,"runtime_adapters/tool_mappings/claude.json",m);},/evidence_produced/i,"required action field"));
test("doctor rejects a mapping missing a required action",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/tool_mappings/claude.json");delete m.actions.dispatch_agent;writeJson(dir,"runtime_adapters/tool_mappings/claude.json",m);},/dispatch_agent/i,"missing required action"));
test("doctor rejects a manifest capability contradicting its mapped action",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/claude.json");m.capabilities.task_tracking="degradable";m.fallbacks.task_tracking="use a ledger file";writeJson(dir,"runtime_adapters/manifests/claude.json",m);},/task_tracking|create_task/i,"manifest/mapping contradiction"));
test("doctor rejects duplicate activation markers",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/gemini.json");m.activation_marker="WCBS_KIT_ACTIVE:claude";writeJson(dir,"runtime_adapters/manifests/gemini.json",m);},/unique|runtime-specific|activation_marker/i,"duplicate marker"));
test("doctor rejects a marker that does not match the documented form",()=>assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/claude.json");m.activation_marker="claude";writeJson(dir,"runtime_adapters/manifests/claude.json",m);},/activation_marker/i,"marker pattern"));
test("doctor rejects a hand-edited capability matrix",()=>assertDoctorRejects((dir)=>{const b=readText(dir,"runtime_adapters/CAPABILITY_MATRIX.md");writeText(dir,"runtime_adapters/CAPABILITY_MATRIX.md",b.replace("**Manual**","**Full**"));},/stale or hand-edited/i,"hand-edited generated file"));
test("doctor rejects a matrix that drops its generated-file warning",()=>assertDoctorRejects((dir)=>{const b=readText(dir,"runtime_adapters/CAPABILITY_MATRIX.md");writeText(dir,"runtime_adapters/CAPABILITY_MATRIX.md",b.replace(/GENERATED FILE/i,"Notes"));},/generated-file warning|stale or hand-edited/i,"missing generated-file warning"));
test("doctor rejects removal of the material-finding re-review rule",()=>assertDoctorRejects((dir)=>{const b=readText(dir,"skills/subagent-driven-development/SKILL.md");writeText(dir,"skills/subagent-driven-development/SKILL.md",b.split("\n").filter((l)=>!l.includes("A fix attempt does not clear a finding")).join("\n"));},/material-finding re-review/i,"stripped re-review rule"));
test("doctor rejects HEAD~1 recommended as review guidance",()=>assertDoctorRejects((dir)=>{const b=readText(dir,"skills/subagent-driven-development/SKILL.md");writeText(dir,"skills/subagent-driven-development/SKILL.md",`${b}\n\nUse \`git diff HEAD~1\` to review the task.\n`);},/shortcut review range/i,"HEAD~1 guidance"));
test("doctor rejects reintroduction of the hand-supplied --diff interface",()=>assertDoctorRejects((dir)=>{const rel="skills/subagent-driven-development/scripts/make-review-package.py";writeText(dir,rel,`${readText(dir,rel)}\n# parser.add_argument("--diff")\n`);},/hand-supplied --diff/i,"--diff reintroduced"));
test("doctor rejects a missing role prompt",()=>assertDoctorRejects((dir)=>fs.rmSync(path.join(dir,"skills/subagent-driven-development/prompts/final-reviewer-prompt.md")),/final-reviewer-prompt/i,"deleted role prompt"));
test("doctor rejects an added npm dependency",()=>assertDoctorRejects((dir)=>{const pkg=readJson(dir,"package.json");pkg.dependencies={"left-pad":"^1.0.0"};writeJson(dir,"package.json",pkg);},/dependencies/i,"third-party dependency"));
test("doctor rejects a near-match activation marker (F-010)",()=>{for(const marker of ["WCBS_KIT_ACTIVE:notclaude","WCBS_KIT_ACTIVE:claude-extra","WCBS_KIT_ACTIVE:xclaude"])assertDoctorRejects((dir)=>{const m=readJson(dir,"runtime_adapters/manifests/claude.json");m.activation_marker=marker;writeJson(dir,"runtime_adapters/manifests/claude.json",m);},/activation_marker must be exactly/i,marker);});
test("doctor rejects a packaged finding with a non-canonical role (F-006)",()=>assertDoctorRejects((dir)=>{installRunBundle(dir);const rel=`${FIXTURE_RUN}/findings.json`;const findings=readJson(dir,rel);findings[0].opened_by="external_reviewer";writeJson(dir,rel,findings);},/violates review-finding\.schema\.json/i,"non-canonical role"));
test("doctor rejects a packaged finding with an undeclared property (F-006)",()=>assertDoctorRejects((dir)=>{installRunBundle(dir);const rel=`${FIXTURE_RUN}/findings.json`;const findings=readJson(dir,rel);findings[0].smuggled_field="hello";writeJson(dir,rel,findings);},/violates review-finding\.schema\.json/i,"undeclared property"));
test("doctor rejects a progress-ledger entry violating its schema (F-006)",()=>assertDoctorRejects((dir)=>{installRunBundle(dir);const rel=`${FIXTURE_RUN}/progress-ledger.jsonl`;const lines=readText(dir,rel).split("\n").filter((l)=>l.trim()!=="");const first=JSON.parse(lines[0]);first.review_verdict="PROBABLY FINE";lines[0]=JSON.stringify(first);writeText(dir,rel,`${lines.join("\n")}\n`);},/violates progress-ledger\.schema\.json/i,"invalid verdict"));
test("doctor rejects a ledger counter below its schema minimum (F-012)",()=>assertDoctorRejects((dir)=>{installRunBundle(dir);const rel=`${FIXTURE_RUN}/progress-ledger.jsonl`;const lines=readText(dir,rel).split("\n").filter((l)=>l.trim()!=="");const first=JSON.parse(lines[0]);first.findings_opened=-1;lines[0]=JSON.stringify(first);writeText(dir,rel,`${lines.join("\n")}\n`);},/below minimum/i,"negative counter"));
test("doctor rejects an invalid timestamp in a durable ledger (F-012)",()=>assertDoctorRejects((dir)=>{installRunBundle(dir);const rel=`${FIXTURE_RUN}/findings.json`;const findings=readJson(dir,rel);findings[0].opened_utc="not-a-date";writeJson(dir,rel,findings);},/not a valid date-time/i,"invalid timestamp"));
test("the committed fixture bundle itself passes the doctor (F-011)",()=>{const dir=fixture();try{installRunBundle(dir);const{code,output}=runDoctor(dir);assert.equal(code,0,output);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test("doctor rejects removal of the doctor or verify script",()=>assertDoctorRejects((dir)=>{const pkg=readJson(dir,"package.json");delete pkg.scripts.verify;writeJson(dir,"package.json",pkg);},/doctor and verify/i,"missing verify script"));
